# Worker name (must match project name in Cloudflare if deploying via Git)
name = "bluesky-bookmark-telegram-bot"

# Entry point for the Worker script relative to this file's location
main = "src/index.js"

# Ensures Worker runtime APIs are compatible with this date's features
# Use a recent date (YYYY-MM-DD) that is not in the future
compatibility_date = "2025-01-01"

# --- Configuration via Cloudflare Dashboard ---
# Secrets (like API tokens, passwords, chat IDs) MUST be configured in the Cloudflare dashboard:
# Worker -> Settings -> Variables -> Environment Variables -> Edit variables -> Add secret
#
# KV Namespace Bindings MUST be configured in the Cloudflare dashboard:
# Worker -> Settings -> Variables -> KV Namespace Bindings -> Add binding

# Optional: Enable logging viewable in the Cloudflare Dashboard
[observability.logs]
enabled = true